image:
  file: .gitpod.Dockerfile
ports:
- port: 8002
  visibility: public
- port: 9001
- port: 15672
  visibility: public
vscode:
  extensions:
    - TabNine.tabnine-vscode@3.4.14
    - felixfbecker.php-debug@1.16.0
tasks:
  - openMode: split-right
    name: "Installer and Services menu"
    command: cat /etc/lighthouse.conf >> /home/gitpod/.bashrc && chmod a+rwx menu.sh && ./menu.sh
  - openMode: tab-after
    name: "Services"
    command: service nginx start &
             rm -f /etc/php/7.4/cli/conf.d/20-tideways.ini && rm -f /etc/php/7.4/fpm/conf.d/20-tideways.ini &&
             sudo cp /workspace/magento2gitpod/sp-redis.conf /etc/supervisor/conf.d/redis.conf &&
             sudo cp /workspace/magento2gitpod/sp-elasticsearch.conf /etc/supervisor/conf.d/elasticsearch.conf &&
             sudo sed -i 's/^\(\[supervisord\]\)$/\1\nnodaemon=true/' /etc/supervisor/supervisord.conf &&
             sudo /etc/init.d/supervisor start & \
             sleep 30;
             sudo supervisorctl stop mysql;
             sudo mv /var/lib/mysql /workspace/magento2gitpod/;
             sed -i 's#/var/lib/mysql#/workspace/magento2gitpod/mysql#g' /etc/mysql/conf.d/mysqld.cnf;
             sudo sed -i 's#/var/lib/mysql#/workspace/magento2gitpod/mysql#g' /etc/supervisor/conf.d/mysql.conf;
             sudo supervisorctl update;
             sudo supervisorctl reload;
             sudo /etc/init.d/rabbitmq-server start & \
             sleep 15;
             sudo rabbitmq-plugins enable rabbitmq_management;
             sudo rabbitmqctl add_user guest guest;
             sudo rabbitmqctl set_user_tags guest administrator;
             sudo rabbitmqctl set_permissions -p / guest ".*" ".*" ".*";
  - name: "Terminal/SSH Start here"
    command: source /etc/lighthouse.conf;clear;echo "Good luck. Happy coding and testing!"
